version: "3.9"

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true  
      - GF_EXPLORE_ENABLED=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
      
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
